---
id: Jwt
name: Jwt
type: library
full: Horde RFC 7519 JSON Web Token (JWT) Library
description: []
list: horde
homepage: http://www.horde.org/libraries/Horde_Jwt
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
authors:
  -
    name: Ralf Lang
    user: ralf.lang
    email: ralf.lang@ralf-lang.de
    role: lead
    active: true
dependencies:
  required:
    php: ^8.1
    ext:
      - json
      - mbstring
keywords:
  - rfc7519
  - claims
  - auth
vendor: horde
quality:
  phpstan:
    level: 1
